# Generated by CoffeeScript 1.7.1
(->
  module.exports = (config) ->
    "use strict"
    config.set
      autoWatch: true
      basePath: "../"
      frameworks: ["jasmine"]
      files: [
        "bower_components/angular/angular.js"
        "bower_components/angular-mocks/angular-mocks.js"
        "bower_components/angular-route/angular-route.js"
        "app/scripts/**/*.js"
        "test/mock/**/*.js"
        "test/spec/**/*.js"
      ]
      exclude: []
      port: 8080
      browsers: ["Chrome"]
      plugins: [
        "karma-phantomjs-launcher"
        "karma-jasmine"
      ]
      singleRun: false
      colors: true
      logLevel: config.LOG_INFO

    return

  return
).call this
